# Generated by Django 4.2 on 2023-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answeroption', models.CharField(max_length=50)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
            ],
        ),
    ]
